/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entornos.git;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appSuma() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.sumar(2, 3));
    }

    @Test
    void appResta() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.resta(5, 4));
    }
}
